import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/Theme-Provider";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import ContactMe from "@/components/ContactMe";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
          <ThemeProvider>
            <div className="relative flex min-h-screen flex-col bg-background">
            <Header />
              <main className="flex-1">
                {children}
              </main>
              <ContactMe />
              <Footer />
            </div>
            <Toaster />
          </ThemeProvider>
      </body>
    </html>
    
  );
}
